<?php
require("../vendor/autoload.php");

use Garphild\SettingsManager\Adapters\JsonFileSettingsAdapter;
use Garphild\SettingsManager\Adapters\JsonFileStructureAdapter;
use Garphild\SettingsManager\SettingsManager;
use PHPUnit\Framework\TestCase;

echo "\n\nSettingsManagerTest\n";

/**
 * @covers Garphild\SettingsManager\SettingsManager
 */
class SettingsManagerAddItemsTest extends TestCase
{
  public $path = './mocks';
  public $structureFileName = 'defaultMultiple.json';
  public $groupFileName = 'defaultMultipleSettingsGroup.json';
  public $userFileName = 'defaultMultipleSettings.json';
  public $groupID = 'guest';
  public $structureAdapter;
  public $groupAdapter;
  public $userAdapter;
  public $manager;

  function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
    $this->structureAdapter = new JsonFileStructureAdapter($this->path, $this->structureFileName);
    $this->groupAdapter = new JsonFileSettingsAdapter($this->path, $this->groupFileName);
    $this->userAdapter = new JsonFileSettingsAdapter($this->path, $this->userFileName);
    $this->manager = new SettingsManager(
    'default',
      $this->structureAdapter,
      [$this->groupID => $this->groupAdapter],
      $this->userAdapter
    );
  }


  /**
   * Нельзя добавлять пользовательское значение, если оно не описано в структуре
   *
   * @covers \Garphild\SettingsManager\SettingsManager::userAddValue
   */
  public function testUserAddItemWrong()
  {
    $this->expectException(Garphild\SettingsManager\Errors\PropertyNotExistException::class);
    $this->manager->userAddValue('testSingleNotExists', "2");
  }

  /**
   * Нельзя добавлять значение для группы, если группы нету в списке
   *
   * @covers \Garphild\SettingsManager\SettingsManager::userAddValue
   */
  public function testGroupAddItemWrong()
  {
    $this->expectException(Garphild\SettingsManager\Errors\PropertyNotExistException::class);
    $this->manager->groupAddValue('testSingleNotExists', "2", "absentGroup");
  }

  /**
   * Нельзя добавлять значение для группы, если свойство не описано в структуре
   *
   * @covers \Garphild\SettingsManager\SettingsManager::userAddValue
   */
  public function testGroupAddItemWrong2()
  {
    $this->expectException(Garphild\SettingsManager\Errors\PropertyNotExistException::class);
    $this->manager->groupAddValue('testSingleNotExists', "2", $this->groupID);
  }

  /**
   * Успешное добавление значения для пользователя
   *
   * @covers \Garphild\SettingsManager\SettingsManager::userAddValue
   */
  public function testUserAddItemSuccess()
  {
    // Проверяем что свойства нет
    $have = $this->manager->userHaveItem('testSingleForUserAdd');
    $this->assertFalse($have);
    $ret = $this->manager->userAddValue('testSingleForUserAdd', "2");
    $this->assertInstanceOf(SettingsManager::class, $ret);
    $have = $this->manager->userHaveItem('testSingleForUserAdd');
    $this->assertTrue($have);
    $res = $this->manager->userGetValue('testSingleForUserAdd', true);
    $this->assertSame("2", $res);
    $res = $this->manager->userGetValue('testSingleForUserAdd', false);
    $this->assertSame("2", $res);
    $res = $this->manager->userGetValue('testSingleForUserAdd');
    $this->assertSame("2", $res);
  }

  /**
   * Успешное добавление значения для пользователя
   *
   * @covers \Garphild\SettingsManager\SettingsManager::groupAddValue
   */
  public function testGroupAddItemSuccess()
  {
    // Проверяем что свойства нет
    $have = $this->manager->groupHaveItem('testSingleForGroupAdd');
    $this->assertFalse($have);
    $ret = $this->manager->groupAddValue('testSingleForGroupAdd', "1", $this->groupID);
    $this->assertInstanceOf(SettingsManager::class, $ret);
    $have = $this->manager->groupHaveItem('testSingleForGroupAdd');
    $this->assertTrue($have);
    $res = $this->manager->groupGetValue('testSingleForGroupAdd', $this->groupID);
    $this->assertSame("1", $res);
    $res = $this->manager->groupGetValue('testSingleForGroupAdd', $this->groupID, false);
    $this->assertSame("1", $res);
    $res = $this->manager->groupGetValue('testSingleForGroupAdd');
    $this->assertSame("1", $res);
    $res = $this->manager->groupGetValue('testSingleForGroupAdd');
    $this->assertSame("1", $res);
  }
}
